spring.application.name=livechatms

spring.datasource.url=jdbc:postgresql://localhost:5331/livechatdb
spring.datasource.username=marques
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true 